[package]
name = "aplin"
version = "0.0.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.3", features = [ "bluetoothd" ] }
tokio = { version = "1.41", features = ["full"] }
clap = { version = "4.5.21", features = ["derive"] }
log = "0.4.22"